// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: css_variables.sql

package db

import (
	"context"
)

const createCSSVariable = `-- name: CreateCSSVariable :exec
INSERT INTO css_variables (name, value, variable_type, is_system)
VALUES (?, ?, ?, ?)
`

type CreateCSSVariableParams struct {
	Name         string `json:"name"`
	Value        string `json:"value"`
	VariableType string `json:"variable_type"`
	IsSystem     bool   `json:"is_system"`
}

func (q *Queries) CreateCSSVariable(ctx context.Context, arg CreateCSSVariableParams) error {
	_, err := q.db.ExecContext(ctx, createCSSVariable,
		arg.Name,
		arg.Value,
		arg.VariableType,
		arg.IsSystem,
	)
	return err
}

const deleteCSSVariable = `-- name: DeleteCSSVariable :exec
DELETE FROM css_variables WHERE name = ? AND is_system = FALSE
`

func (q *Queries) DeleteCSSVariable(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteCSSVariable, name)
	return err
}

const getAllCSSVariables = `-- name: GetAllCSSVariables :many
SELECT name, value, variable_type, is_system, created_at, updated_at FROM css_variables ORDER BY variable_type, name
`

func (q *Queries) GetAllCSSVariables(ctx context.Context) ([]CssVariable, error) {
	rows, err := q.db.QueryContext(ctx, getAllCSSVariables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CssVariable{}
	for rows.Next() {
		var i CssVariable
		if err := rows.Scan(
			&i.Name,
			&i.Value,
			&i.VariableType,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCSSVariableByName = `-- name: GetCSSVariableByName :one
SELECT name, value, variable_type, is_system, created_at, updated_at FROM css_variables WHERE name = ?
`

func (q *Queries) GetCSSVariableByName(ctx context.Context, name string) (CssVariable, error) {
	row := q.db.QueryRowContext(ctx, getCSSVariableByName, name)
	var i CssVariable
	err := row.Scan(
		&i.Name,
		&i.Value,
		&i.VariableType,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCSSVariablesByType = `-- name: GetCSSVariablesByType :many
SELECT name, value, variable_type, is_system, created_at, updated_at FROM css_variables WHERE variable_type = ? ORDER BY name
`

func (q *Queries) GetCSSVariablesByType(ctx context.Context, variableType string) ([]CssVariable, error) {
	rows, err := q.db.QueryContext(ctx, getCSSVariablesByType, variableType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CssVariable{}
	for rows.Next() {
		var i CssVariable
		if err := rows.Scan(
			&i.Name,
			&i.Value,
			&i.VariableType,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCSSVariable = `-- name: UpdateCSSVariable :exec
UPDATE css_variables
SET value = ?, variable_type = ?, updated_at = CURRENT_TIMESTAMP
WHERE name = ? AND is_system = FALSE
`

type UpdateCSSVariableParams struct {
	Value        string `json:"value"`
	VariableType string `json:"variable_type"`
	Name         string `json:"name"`
}

func (q *Queries) UpdateCSSVariable(ctx context.Context, arg UpdateCSSVariableParams) error {
	_, err := q.db.ExecContext(ctx, updateCSSVariable, arg.Value, arg.VariableType, arg.Name)
	return err
}
