// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lead.sql

package db

import (
	"context"
)

const createLead = `-- name: CreateLead :exec
INSERT INTO leads (
  id,
  first_name,
  last_name,
  email,
  phone,
  company,
  message,
  status,
  source
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9
)
`

type CreateLeadParams struct {
	ID        string  `json:"id"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Email     string  `json:"email"`
	Phone     *string `json:"phone"`
	Company   *string `json:"company"`
	Message   *string `json:"message"`
	Status    string  `json:"status"`
	Source    *string `json:"source"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) error {
	_, err := q.db.ExecContext(ctx, createLead,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Company,
		arg.Message,
		arg.Status,
		arg.Source,
	)
	return err
}

const listLeadsFiltered = `-- name: ListLeadsFiltered :many
SELECT
  id,
  first_name,
  last_name,
  email,
  phone,
  company,
  message,
  status,
  source,
  created_at
FROM leads
WHERE
  (?1 IS NULL OR status = ?2)
  AND (?3 IS NULL OR created_at >= ?4)
  AND (?5 IS NULL OR created_at <= ?6)
  AND (
    ?7 IS NULL
    OR lower(first_name) LIKE lower('%' || ?8 || '%')
    OR lower(last_name) LIKE lower('%' || ?9 || '%')
    OR lower(email) LIKE lower('%' || ?10 || '%')
  )
ORDER BY created_at DESC
LIMIT ?11 OFFSET ?12
`

type ListLeadsFilteredParams struct {
	Column1     interface{} `json:"column_1"`
	Status      string      `json:"status"`
	Column3     interface{} `json:"column_3"`
	CreatedAt   string      `json:"created_at"`
	Column5     interface{} `json:"column_5"`
	CreatedAt_2 string      `json:"created_at_2"`
	Column7     interface{} `json:"column_7"`
	Column8     *string     `json:"column_8"`
	Column9     *string     `json:"column_9"`
	Column10    *string     `json:"column_10"`
	Limit       int64       `json:"limit"`
	Offset      int64       `json:"offset"`
}

func (q *Queries) ListLeadsFiltered(ctx context.Context, arg ListLeadsFilteredParams) ([]Lead, error) {
	rows, err := q.db.QueryContext(ctx, listLeadsFiltered,
		arg.Column1,
		arg.Status,
		arg.Column3,
		arg.CreatedAt,
		arg.Column5,
		arg.CreatedAt_2,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Company,
			&i.Message,
			&i.Status,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
