// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateCSSVariable(ctx context.Context, arg CreateCSSVariableParams) error
	CreateLead(ctx context.Context, arg CreateLeadParams) error
	DeleteCSSVariable(ctx context.Context, name string) error
	GetAllCSSVariables(ctx context.Context) ([]CssVariable, error)
	GetCSSVariableByName(ctx context.Context, name string) (CssVariable, error)
	GetCSSVariablesByType(ctx context.Context, variableType string) ([]CssVariable, error)
	ListLeadsFiltered(ctx context.Context, arg ListLeadsFilteredParams) ([]Lead, error)
	UpdateCSSVariable(ctx context.Context, arg UpdateCSSVariableParams) error
}

var _ Querier = (*Queries)(nil)
